"""Generate ap_item_map.h: AP item id -> engine item id (0..106), or -1 if none.

Joins research/kyra1_items.json (crosswalk ap_id<->engine_id) with the apworld's
ITEM_TABLE (apworld/kyrandia/data.py), resolving the apworld's extra ids by name.
Output: build/deps/ap/bridge/ap_item_map.h (on the engine include path).
"""
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
cw = json.load(open(ROOT / "research" / "kyra1_items.json", encoding="utf-8"))

base = {}            # ap_id -> engine_id (from the crosswalk)
name_to_engine = {}  # lowercased engine_name -> engine_id (first = ladder head)
for it in cw["items"]:
    if it.get("ap_id"):
        base.setdefault(it["ap_id"], it["engine_id"])
    name_to_engine.setdefault(it["engine_name"].lower(), it["engine_id"])

spec = importlib.util.spec_from_file_location("kdata", ROOT / "apworld" / "kyrandia" / "data.py")
D = importlib.util.module_from_spec(spec)
spec.loader.exec_module(D)

# apworld name (lower) -> engine name (lower) where they differ
ALIAS = {
    "magic scroll": "scroll",
    "lavender rose": "rose",
    "sceptre": "royal sceptre",
    "crown": "royal crown",
    "magic water": "magical water",
    "hidden key": "obsidion key",
    "loose gem": "garnet",
}

rows = []      # (ap_id, engine_id, name)
unmapped = []
for name, (ap_id, _cls) in D.ITEM_TABLE.items():
    if ap_id in base:
        rows.append((ap_id, base[ap_id], name))
        continue
    key = ALIAS.get(name.lower(), name.lower())
    eng = name_to_engine.get(key)
    if eng is not None:
        rows.append((ap_id, eng, name))
    else:
        unmapped.append((ap_id, name))

rows.sort()
lines = [
    "#ifndef KYRA_AP_ITEM_MAP_H",
    "#define KYRA_AP_ITEM_MAP_H",
    "// Auto-generated by pyscripts/gen_ap_item_map.py — AP item id -> engine item id (0..106), or -1.",
    "// Lets the client translate items received from Archipelago into engine item grants.",
    "static inline int apItemToEngineId(long long apId) {",
    "\tswitch (apId) {",
]
for ap_id, eng, name in rows:
    lines.append("\tcase %d: return %d; // %s" % (ap_id, eng, name))
lines += ["\tdefault: return -1;", "\t}", "}", "#endif", ""]

out = ROOT / "build" / "deps" / "ap" / "bridge" / "ap_item_map.h"
out.write_text("\n".join(lines), encoding="utf-8")
print("Wrote %s with %d mapped items" % (out, len(rows)))
if unmapped:
    print("Unmapped (no engine item, will be skipped on receive):")
    for ap_id, name in unmapped:
        print("  %d  %s" % (ap_id, name))
